a = input('Digite algo: ')
print(f'O tipo primitivo desse valor é {type (a)}')
print(f'Só tem espaços? {a.isspace()}')
print(f'É um números? {a.isnumeric()}')
print(f'é uma palavra? {a.isalpha()}')
print(f'é um alfanúmerico? {a.isalnum()}')
print(f'Está tudo em maisculo? {a.isupper()}')
print(f'Está tudo em minusculo? {a.islower()}')
print(f'Pode ser imprimido? {a.isprintable()}')
print(f'Está capitalizada? {a.istitle()}')   
input("PRESSIONE ENTER PARA FINALIZAR ;)")